Web/MiniProject/Controllers/TabPembayaranController.cs
using Microsoft.AspNetCore.Mvc;

namespace MiniProject.Controllers
{
    public class TabPembayaranController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

      
    }
}

Web/MiniProject/Views/TabPembayaran/Index.cshtml
<div class="wrapper">
    <div class="content-wrapper">
        <nav class="navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <ul class="navbar-nav d-flex">
                    <li class="nav-item jus">
                        <a class="nav-link me-2 " href="#" role="button">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" role="button">Alamat</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="TabPembayaran" asp-action="Index" role="button">Pembayaran</a>
                    </li>
                </ul>
            </ul>
        </nav>
        <section class="content">
            <div class="container-fluid">
                <aside class="main-sidebar sidebar-dark-primary elevation-4 mt-auto">
                    <!-- Brand Logo -->
                    <ul class="nav nav-pills nav-sidebar flex-column mt-5" data-widget="treeview" role="menu" data-accordion="false">
                        <a href="#" class="brand-link" id="edit_foto">
                            <img src="Foto/pasien.png"  class="brand img-circle elevation-5 text-center" height="200px" style="opacity: .8" />
                            <br />
                           
                        </a>
                         <h2 class="font-weight-light text-center text-white">User</h2>

                        <li class="nav-item mt-1 menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">

                                        <i class="fas fa-male nav-icon"></i>
                                        <p>Pasien</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-capsules nav-icon"></i>
                                        <p>Pembelian Obat</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-user-clock nav-icon"></i>
                                        <p>Rencana Kedatangan</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-user-md nav-icon"></i>
                                        <p>Riwayat Chat Dokter</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <!-- /.sidebar -->
                </aside>
                <div class="card mt-1">
                    <div class="card-header">
                        Kartu Kredit / Debit (2/4) Tersimpan

                    </div>
                    <div class="card-body">
                        <form class="text-end">
                            <a href="#" class="btn btn-primary">Tambah</a>
                        </form>

                        <p class="card-text text-grey">xxxx-xxxxx-xxxxx 7245</p>
                        <p class="card-text text-grey">xxxx-xxxxx-xxxxx 7245</p>

                    </div>
                    <div class="card-footer text-muted">
                    </div>
                </div>
                <div class="card mt-1">
                    <div class="card-header">
                        Dompet Sehat
                    </div>
                    <div class="card-body">

                        <form class="text-end" id="button">
                            <input type="button" id="saldo" name="saldo" class="btn btn-primary" value="Saldo" />
                            <input type="button" id="pin" name="pin" class="btn btn-primary" margin-left: 10px;" value="Pin" />
                            <input type="button" class="btn btn-primary" id="aktif" onclick="aktif()" value="Aktifkan" />
                        </form>

                        <h2 class="card-text text-blue">Rp. 2.500.000</h2>
                    </div>
                    <div class="card-footer text-muted">
                    </div>
                </div>
                @*Content Goes Here*@
            </div>
        </section>
    </div>
</div>
@section Scripts{
<script type="text/javascript">
          $('input[id="saldo"]').attr('disabled', true);
          $('input[id="pin"]').attr('disabled', true);

        $("#aktif").click(function(){
               $('input[id="saldo"]').attr('disabled', false);
               $('input[id="pin"]').attr('disabled', false);
               $('input[id="aktif"]').val('Tutup');
         })


</script>
}